---
- name: import epel key
  command: /bin/rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6

- name: import remi key
  command: /bin/rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-remi

- name: import zabbix key
  command: /bin/rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX

- name: restart sshd
  service: name=sshd state=restarted
