---

- name: be sure nginx repository is installed
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
  tags: nginx

- name: disable nginx repository
  ini_file: dest=/etc/yum.repos.d/nginx.repo section="nginx" option="enabled" value="0"
  tags: nginx

- name: be sure nginx is installed
  yum: name={{item}} state=installed enablerepo=nginx
  with_items:
    - nginx
  notify:
    - restart nginx
  tags: nginx

- name: be sure nginx is configured
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags: nginx

- name: be sure nginx conf.d is configured
  template: src=static.conf.j2 dest=/etc/nginx/conf.d/static.conf
  notify:
    - restart nginx
  tags: nginx

- name: move default.conf to default.conf.org
  command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.org
  notify:
    - restart nginx
  tags: nginx

- name: be sure nginx is running and enabled
  service: name=nginx state=running enabled=yes
  tags: nginx

