---

# Install ZABBIX agent


- name: get zabbix-repo rpm RHEL6
  get_url: dest={{ ansible_cache_dir }}/zabbix-release-2.2-1.el6.noarch.rpm  url=http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 6
  tags: zabbix-common

- name: get http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
  get_url: dest={{ ansible_cache_dir }}/RPM-GPG-KEY-ZABBIX  url=http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 6
  tags: zabbix-common
  register: get_key_result

- name: import ZABBIX key
  command: /bin/rpm --import {{ ansible_cache_dir }}/RPM-GPG-KEY-ZABBIX
  when: get_key_result.changed
  tags: zabbix-common

- name: install zabbix-repos
  yum: pkg={{ ansible_cache_dir }}/zabbix-release-2.2-1.el6.noarch.rpm state=installed disable_gpg_check=yes
  tags: zabbix-common

- name: Change yum ZABBIX repo conf
  copy: >
    src=zabbix.repo
    dest=/etc/yum.repos.d/zabbix.repo
  tags: zabbix-common

- name: disable zabbix repository
  ini_file: dest=/etc/yum.repos.d/zabbix.repo section="zabbix" option="enabled" value="0"
  ini_file: dest=/etc/yum.repos.d/zabbix.repo section="zabbix-non-supported" option="enabled" value="0"
  tags: zabbix-common

- name: Install ZABBIX agent/sender/get
  yum: >
    enablerepo=zabbix,zabbix-non-supported
    name={{item}} state=installed
  with_items:
    - zabbix-agent
    - zabbix-get
    - zabbix-sender
  tags: zabbix-common

- name: Configure ZABBIX agent
  template: >
    dest=/etc/zabbix/zabbix_agentd.conf
    src=zabbix_agentd.conf.j2
  tags: zabbix-common

- name: Start ZABBIX agent service
  service: name=zabbix-agent state=started enabled=yes
  tags: zabbix-common

- name: Configure ZABBIX agent conf.d misc
  template: >
    dest=/etc/zabbix/zabbix_agentd.d/userparameter_misc.conf
    src=userparameter_misc.conf.j2
  tags: zabbix-agent-confd-misc

- name: Configure ZABBIX agent conf.d mysqld
  template: >
    dest=/etc/zabbix/zabbix_agentd.d/userparameter_mysqld.conf
    src=userparameter_mysqld.conf.j2
  tags: zabbix-agent-confd-mysqld

- name: Configure ZABBIX agent conf.d nginx
  template: >
    dest=/etc/zabbix/zabbix_agentd.d/userparameter_nginx.conf
    src=userparameter_nginx.conf.j2
  notify:
    - restart zabbix-agent
  tags: zabbix-agent-confd-nginx
